import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    lib: "src/lib.ts",
    cli: "src/cli.ts",
    "commands/start": "src/commands/start.ts",
    "commands/setup": "src/commands/setup.ts",
    "commands/stop": "src/commands/stop.ts",
    "commands/status": "src/commands/status.ts",
    "commands/utils": "src/commands/utils.ts",
  },
  format: ["esm"],
  dts: true,
  sourcemap: true,
  clean: true,
  outDir: "dist",
  target: "node20",
  splitting: true,
  // Mark all dependencies as external (not bundled)
  external: [
    // Core deps
    "@anthropic-ai/sdk",
    "openai",
    "hono",
    "hono/cors",
    "hono/logger",
    "hono/bun",
    "drizzle-orm",
    "drizzle-orm/postgres-js",
    "postgres",
    "ioredis",
    "bullmq",
    "zod",
    "nanoid",
    "uuid",
    "date-fns",
    "marked",
    "node-cron",
    "glob",
    // Optional channel deps
    "discord.js",
    "@discordjs/voice",
    "grammy",
    "@grammyjs/files",
    "@slack/bolt",
    "@slack/web-api",
    "@whiskeysockets/baileys",
    "@hapi/boom",
    "qrcode-terminal",
    // Optional integration deps
    "playwright",
    "tesseract.js",
    "screenshot-desktop",
    "imapflow",
    "mailparser",
    "nodemailer",
    "octokit",
    "@octokit/webhooks",
    "exceljs",
    "mammoth",
    "pdf-parse",
    "pdfkit",
  ],
});
