/**
 * Cloud Storage Integration
 *
 * Provides unified cloud storage integration for Moltbot,
 * supporting Google Drive, Dropbox, and a unified interface.
 */

// Google Drive exports
export {
  initGoogleDrive,
  isGoogleDriveInitialized,
  resetGoogleDrive,
  getAuthorizationUrl as getGoogleDriveAuthUrl,
  exchangeCodeForTokens as exchangeGoogleDriveCode,
  listFiles as listGoogleDriveFiles,
  listAllFiles as listAllGoogleDriveFiles,
  getFile as getGoogleDriveFile,
  searchFiles as searchGoogleDriveFiles,
  uploadFile as uploadGoogleDriveFile,
  uploadLocalFile as uploadLocalGoogleDriveFile,
  downloadFile as downloadGoogleDriveFile,
  createFolder as createGoogleDriveFolder,
  deleteFile as deleteGoogleDriveFile,
  restoreFile as restoreGoogleDriveFile,
  moveFile as moveGoogleDriveFile,
  renameFile as renameGoogleDriveFile,
  copyFile as copyGoogleDriveFile,
  shareFile as shareGoogleDriveFile,
  getShareableLink as getGoogleDriveShareableLink,
  unshareFile as unshareGoogleDriveFile,
  listPermissions as listGoogleDrivePermissions,
  syncFolder as syncGoogleDriveFolder,
  getStorageQuota as getGoogleDriveStorageQuota,
  type GoogleDriveConfig,
  type DriveFile,
  type DriveUser,
  type DrivePermission,
  type ListFilesOptions as GoogleDriveListOptions,
  type ListFilesResult as GoogleDriveListResult,
  type UploadOptions as GoogleDriveUploadOptions,
  type DownloadOptions as GoogleDriveDownloadOptions,
  type ShareOptions as GoogleDriveShareOptions,
  type SyncOptions as GoogleDriveSyncOptions,
  type SyncResult as GoogleDriveSyncResult,
} from "./google-drive";

// Dropbox exports
export {
  initDropbox,
  isDropboxInitialized,
  resetDropbox,
  getAuthorizationUrl as getDropboxAuthUrl,
  exchangeCodeForTokens as exchangeDropboxCode,
  listFolder as listDropboxFolder,
  listFolderContinue as continueDropboxListing,
  listAllFiles as listAllDropboxFiles,
  getMetadata as getDropboxMetadata,
  searchFiles as searchDropboxFiles,
  uploadFile as uploadDropboxFile,
  uploadLocalFile as uploadLocalDropboxFile,
  uploadLargeFile as uploadLargeDropboxFile,
  downloadFile as downloadDropboxFile,
  createFolder as createDropboxFolder,
  deleteFile as deleteDropboxFile,
  permanentlyDelete as permanentlyDeleteDropboxFile,
  moveFile as moveDropboxFile,
  copyFile as copyDropboxFile,
  getTemporaryLink as getDropboxTemporaryLink,
  createSharedLink as createDropboxSharedLink,
  getShareableLink as getDropboxShareableLink,
  listSharedLinks as listDropboxSharedLinks,
  revokeSharedLink as revokeDropboxSharedLink,
  getRevisions as getDropboxRevisions,
  restoreFile as restoreDropboxFile,
  syncFolder as syncDropboxFolder,
  getSpaceUsage as getDropboxSpaceUsage,
  getCurrentAccount as getDropboxAccount,
  type DropboxConfig,
  type DropboxFile,
  type DropboxFolder,
  type DropboxEntry,
  type ListFolderOptions as DropboxListOptions,
  type ListFolderResult as DropboxListResult,
  type UploadOptions as DropboxUploadOptions,
  type DownloadOptions as DropboxDownloadOptions,
  type ShareOptions as DropboxShareOptions,
  type SharedLink as DropboxSharedLink,
  type SyncOptions as DropboxSyncOptions,
  type SyncResult as DropboxSyncResult,
  type SearchResult as DropboxSearchResult,
  type SpaceUsage as DropboxSpaceUsage,
} from "./dropbox";

// Unified interface exports
export {
  UnifiedCloudStorage,
  getUnifiedCloudStorage,
  createUnifiedCloudStorage,
  resetUnifiedCloudStorage,
  type CloudProvider,
  type CloudFile,
  type CloudFolder,
  type ListOptions,
  type ListResult,
  type UploadOptions,
  type DownloadOptions,
  type ShareOptions,
  type ShareResult,
  type SyncOptions,
  type SyncResult,
  type ProviderConfig,
  type StorageQuota,
} from "./unified";

// Import modules for default export
import * as googleDriveModule from "./google-drive";
import * as dropboxModule from "./dropbox";
import * as unifiedModule from "./unified";

// Default export with commonly used functions
export default {
  // Unified interface
  getUnifiedStorage: unifiedModule.getUnifiedCloudStorage,
  createUnifiedStorage: unifiedModule.createUnifiedCloudStorage,
  resetUnifiedStorage: unifiedModule.resetUnifiedCloudStorage,

  // Google Drive
  googleDrive: {
    init: googleDriveModule.initGoogleDrive,
    isInitialized: googleDriveModule.isGoogleDriveInitialized,
    reset: googleDriveModule.resetGoogleDrive,
    getAuthUrl: googleDriveModule.getAuthorizationUrl,
    exchangeCode: googleDriveModule.exchangeCodeForTokens,
    list: googleDriveModule.listFiles,
    listAll: googleDriveModule.listAllFiles,
    get: googleDriveModule.getFile,
    search: googleDriveModule.searchFiles,
    upload: googleDriveModule.uploadFile,
    uploadLocal: googleDriveModule.uploadLocalFile,
    download: googleDriveModule.downloadFile,
    createFolder: googleDriveModule.createFolder,
    delete: googleDriveModule.deleteFile,
    restore: googleDriveModule.restoreFile,
    move: googleDriveModule.moveFile,
    rename: googleDriveModule.renameFile,
    copy: googleDriveModule.copyFile,
    share: googleDriveModule.shareFile,
    getShareableLink: googleDriveModule.getShareableLink,
    unshare: googleDriveModule.unshareFile,
    listPermissions: googleDriveModule.listPermissions,
    sync: googleDriveModule.syncFolder,
    getQuota: googleDriveModule.getStorageQuota,
  },

  // Dropbox
  dropbox: {
    init: dropboxModule.initDropbox,
    isInitialized: dropboxModule.isDropboxInitialized,
    reset: dropboxModule.resetDropbox,
    getAuthUrl: dropboxModule.getAuthorizationUrl,
    exchangeCode: dropboxModule.exchangeCodeForTokens,
    list: dropboxModule.listFolder,
    listAll: dropboxModule.listAllFiles,
    get: dropboxModule.getMetadata,
    search: dropboxModule.searchFiles,
    upload: dropboxModule.uploadFile,
    uploadLocal: dropboxModule.uploadLocalFile,
    uploadLarge: dropboxModule.uploadLargeFile,
    download: dropboxModule.downloadFile,
    createFolder: dropboxModule.createFolder,
    delete: dropboxModule.deleteFile,
    permanentlyDelete: dropboxModule.permanentlyDelete,
    move: dropboxModule.moveFile,
    copy: dropboxModule.copyFile,
    getTemporaryLink: dropboxModule.getTemporaryLink,
    createSharedLink: dropboxModule.createSharedLink,
    getShareableLink: dropboxModule.getShareableLink,
    listSharedLinks: dropboxModule.listSharedLinks,
    revokeSharedLink: dropboxModule.revokeSharedLink,
    getRevisions: dropboxModule.getRevisions,
    restore: dropboxModule.restoreFile,
    sync: dropboxModule.syncFolder,
    getSpaceUsage: dropboxModule.getSpaceUsage,
    getAccount: dropboxModule.getCurrentAccount,
  },
};
