/**
 * OpenSentinel Setup Wizard
 *
 * Interactive setup that installs dependencies, configures the database,
 * generates config, and optionally installs a system service.
 */

import { writeFileSync, chmodSync, existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import {
  prompt,
  confirm,
  exec,
  which,
  detectPlatform,
  getConfigDir,
  getPackageRoot,
  getMigrationsDir,
  checkPostgres,
  checkRedis,
  colors,
  printBanner,
  type Platform,
} from "./utils";

export default async function setup() {
  printBanner();
  console.log(`${colors.bold}Setup Wizard${colors.reset}\n`);

  const platform = detectPlatform();
  if (platform.os === "other") {
    console.log(`${colors.yellow}Warning: Only Linux and macOS are fully supported.`);
    console.log(`On Windows, use WSL or Docker.${colors.reset}\n`);
  }

  const configDir = getConfigDir();
  console.log(`${colors.dim}Config directory: ${configDir}${colors.reset}\n`);

  // ── Step 1: API Keys ─────────────────────────────────────────────────────

  console.log(`${colors.cyan}${colors.bold}[1/5] API Keys${colors.reset}\n`);

  let claudeKey = process.env.CLAUDE_API_KEY || "";
  if (!claudeKey) {
    claudeKey = await prompt(`  Claude API Key ${colors.red}(required)${colors.reset}: `);
    if (!claudeKey) {
      console.error(`\n${colors.red}Claude API Key is required. Get one at https://console.anthropic.com${colors.reset}`);
      process.exit(1);
    }
  } else {
    console.log(`  Claude API Key: ${colors.green}configured${colors.reset} (***${claudeKey.slice(-4)})`);
  }

  const telegramToken = process.env.TELEGRAM_BOT_TOKEN || await prompt(`  Telegram Bot Token ${colors.dim}(optional, Enter to skip)${colors.reset}: `);
  const telegramChatId = telegramToken ? (process.env.TELEGRAM_CHAT_ID || await prompt(`  Telegram Chat ID: `)) : "";
  const discordToken = process.env.DISCORD_BOT_TOKEN || await prompt(`  Discord Bot Token ${colors.dim}(optional, Enter to skip)${colors.reset}: `);
  const discordClientId = discordToken ? (process.env.DISCORD_CLIENT_ID || await prompt(`  Discord Client ID: `)) : "";
  const discordGuildId = discordToken ? (process.env.DISCORD_GUILD_ID || await prompt(`  Discord Guild ID: `)) : "";
  const discordAllowedUsers = discordToken ? (process.env.DISCORD_ALLOWED_USER_IDS || await prompt(`  Discord Allowed User IDs ${colors.dim}(comma-separated)${colors.reset}: `)) : "";
  const openaiKey = process.env.OPENAI_API_KEY || await prompt(`  OpenAI API Key ${colors.dim}(optional, for voice/images)${colors.reset}: `);
  const elevenlabsKey = process.env.ELEVENLABS_API_KEY || await prompt(`  ElevenLabs API Key ${colors.dim}(optional, for TTS)${colors.reset}: `);
  const elevenlabsVoice = elevenlabsKey ? (process.env.ELEVENLABS_VOICE_ID || await prompt(`  ElevenLabs Voice ID: `)) : "";

  console.log(`\n${colors.green}  API keys collected.${colors.reset}\n`);

  // ── Step 2: Infrastructure ────────────────────────────────────────────────

  console.log(`${colors.cyan}${colors.bold}[2/5] Infrastructure${colors.reset}\n`);

  const { databaseUrl } = await setupPostgres(platform);
  const { redisUrl } = await setupRedis(platform);

  // ── Step 3: Database Migrations ───────────────────────────────────────────

  console.log(`\n${colors.cyan}${colors.bold}[3/5] Database${colors.reset}\n`);

  await runMigrations(databaseUrl);

  // ── Step 4: Generate Config ───────────────────────────────────────────────

  console.log(`\n${colors.cyan}${colors.bold}[4/5] Configuration${colors.reset}\n`);

  const port = process.env.PORT || "8030";

  const envContent = `# OpenSentinel Configuration
# Generated by opensentinel setup on ${new Date().toISOString()}

# Core AI
CLAUDE_API_KEY=${claudeKey}
${openaiKey ? `OPENAI_API_KEY=${openaiKey}` : "# OPENAI_API_KEY="}
${elevenlabsKey ? `ELEVENLABS_API_KEY=${elevenlabsKey}` : "# ELEVENLABS_API_KEY="}
${elevenlabsVoice ? `ELEVENLABS_VOICE_ID=${elevenlabsVoice}` : "# ELEVENLABS_VOICE_ID="}

# Telegram
${telegramToken ? `TELEGRAM_BOT_TOKEN=${telegramToken}` : "# TELEGRAM_BOT_TOKEN="}
${telegramChatId ? `TELEGRAM_CHAT_ID=${telegramChatId}` : "# TELEGRAM_CHAT_ID="}

# Discord
${discordToken ? `DISCORD_BOT_TOKEN=${discordToken}` : "# DISCORD_BOT_TOKEN="}
${discordClientId ? `DISCORD_CLIENT_ID=${discordClientId}` : "# DISCORD_CLIENT_ID="}
${discordGuildId ? `DISCORD_GUILD_ID=${discordGuildId}` : "# DISCORD_GUILD_ID="}
${discordAllowedUsers ? `DISCORD_ALLOWED_USER_IDS=${discordAllowedUsers}` : "# DISCORD_ALLOWED_USER_IDS="}

# Database & Cache
DATABASE_URL=${databaseUrl}
REDIS_URL=${redisUrl}

# Server
PORT=${port}
NODE_ENV=production
`;

  const envPath = join(configDir, ".env");
  writeFileSync(envPath, envContent);
  chmodSync(envPath, 0o600);
  console.log(`  Config written to ${colors.green}${envPath}${colors.reset}`);

  // ── Step 5: System Service ────────────────────────────────────────────────

  console.log(`\n${colors.cyan}${colors.bold}[5/5] System Service${colors.reset}\n`);

  await setupDaemon(platform, configDir);

  // ── Done ──────────────────────────────────────────────────────────────────

  console.log(`
${colors.green}${colors.bold}Setup complete!${colors.reset}

${colors.bold}Quick reference:${colors.reset}
  opensentinel start     Start the server
  opensentinel stop      Stop the service
  opensentinel status    Check health
  opensentinel help      Show all commands

${colors.bold}Config:${colors.reset} ${envPath}
${colors.bold}Docs:${colors.reset}   https://docs.opensentinel.ai
`);
}

// ── PostgreSQL Setup ─────────────────────────────────────────────────────────

async function setupPostgres(platform: Platform): Promise<{ databaseUrl: string }> {
  const pg = await checkPostgres();

  if (pg.running) {
    console.log(`  PostgreSQL: ${colors.green}running${colors.reset} (port ${pg.port})`);
    const useExisting = await confirm("  Use existing PostgreSQL?");
    if (useExisting) {
      return await configureExistingPostgres(pg.port);
    }
  } else if (pg.installed) {
    console.log(`  PostgreSQL: ${colors.yellow}installed but not running${colors.reset}`);
    const startIt = await confirm("  Start PostgreSQL?");
    if (startIt) {
      await startPostgres(platform);
      return await configureExistingPostgres(5432);
    }
  } else {
    console.log(`  PostgreSQL: ${colors.red}not found${colors.reset}`);
  }

  const install = await confirm("  Install PostgreSQL 16 + pgvector?");
  if (!install) {
    console.log(`\n${colors.yellow}  Skipping PostgreSQL. The app will start but memory and history won't persist.${colors.reset}`);
    return { databaseUrl: "postgresql://localhost:5432/opensentinel" };
  }

  return await installPostgres(platform);
}

async function configureExistingPostgres(port: number): Promise<{ databaseUrl: string }> {
  // Try to create the database and user
  const dbUser = "opensentinel";
  const dbPass = "opensentinel";
  const dbName = "opensentinel";

  console.log(`  Creating database '${dbName}'...`);

  // Try as postgres superuser first (common on Linux)
  try {
    await exec(`sudo -u postgres psql -c "SELECT 1 FROM pg_roles WHERE rolname='${dbUser}'" 2>/dev/null | grep -q 1 || sudo -u postgres psql -c "CREATE USER ${dbUser} WITH PASSWORD '${dbPass}'"`, { throws: false });
    await exec(`sudo -u postgres psql -c "SELECT 1 FROM pg_database WHERE datname='${dbName}'" 2>/dev/null | grep -q 1 || sudo -u postgres psql -c "CREATE DATABASE ${dbName} OWNER ${dbUser}"`, { throws: false });
    await exec(`sudo -u postgres psql -d ${dbName} -c "CREATE EXTENSION IF NOT EXISTS vector" 2>/dev/null`, { throws: false });
    console.log(`  ${colors.green}Database ready.${colors.reset}`);
  } catch {
    // On macOS or systems where current user is superuser
    try {
      await exec(`psql -c "SELECT 1 FROM pg_roles WHERE rolname='${dbUser}'" postgres 2>/dev/null | grep -q 1 || createuser ${dbUser} 2>/dev/null`, { throws: false });
      await exec(`psql -c "SELECT 1 FROM pg_database WHERE datname='${dbName}'" postgres 2>/dev/null | grep -q 1 || createdb -O ${dbUser} ${dbName} 2>/dev/null`, { throws: false });
      await exec(`psql -d ${dbName} -c "CREATE EXTENSION IF NOT EXISTS vector" 2>/dev/null`, { throws: false });
      console.log(`  ${colors.green}Database ready.${colors.reset}`);
    } catch {
      console.log(`  ${colors.yellow}Could not auto-configure database. You may need to create it manually.${colors.reset}`);
    }
  }

  return { databaseUrl: `postgresql://${dbUser}:${dbPass}@localhost:${port}/${dbName}` };
}

async function startPostgres(platform: Platform) {
  if (platform.os === "linux") {
    await exec("sudo systemctl start postgresql", { throws: false });
  } else if (platform.os === "darwin") {
    await exec("brew services start postgresql@16", { throws: false });
  }
}

async function installPostgres(platform: Platform): Promise<{ databaseUrl: string }> {
  console.log(`\n  Installing PostgreSQL 16 + pgvector...`);

  if (platform.packageManager === "apt") {
    // Check if PostgreSQL APT repo is available for PG16
    const hasRepo = await exec("apt-cache show postgresql-16 2>/dev/null", { throws: false });
    if (hasRepo.exitCode !== 0) {
      console.log(`  Adding PostgreSQL APT repository...`);
      await exec(`sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'`);
      await exec("curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg");
    }
    await exec("sudo apt-get update -qq");
    await exec("sudo apt-get install -y postgresql-16 postgresql-16-pgvector");
    await exec("sudo systemctl enable postgresql");
    await exec("sudo systemctl start postgresql");
  } else if (platform.packageManager === "brew") {
    await exec("brew install postgresql@16 pgvector");
    await exec("brew services start postgresql@16");
    // Wait for PG to start
    await new Promise((r) => setTimeout(r, 2000));
  } else if (platform.packageManager === "dnf") {
    await exec("sudo dnf install -y postgresql16-server postgresql16-pgvector");
    await exec("sudo postgresql-setup --initdb 2>/dev/null || true");
    await exec("sudo systemctl enable postgresql");
    await exec("sudo systemctl start postgresql");
  } else {
    console.log(`  ${colors.yellow}Unsupported package manager. Please install PostgreSQL 16 + pgvector manually.${colors.reset}`);
    return { databaseUrl: "" };
  }

  console.log(`  ${colors.green}PostgreSQL installed.${colors.reset}`);
  return await configureExistingPostgres(5432);
}

// ── Redis Setup ──────────────────────────────────────────────────────────────

async function setupRedis(platform: Platform): Promise<{ redisUrl: string }> {
  const redis = await checkRedis();

  if (redis.running) {
    console.log(`  Redis: ${colors.green}running${colors.reset} (port ${redis.port})`);
    return { redisUrl: `redis://localhost:${redis.port}` };
  } else if (redis.installed) {
    console.log(`  Redis: ${colors.yellow}installed but not running${colors.reset}`);
    const startIt = await confirm("  Start Redis?");
    if (startIt) {
      await startRedis(platform);
      return { redisUrl: "redis://localhost:6379" };
    }
  } else {
    console.log(`  Redis: ${colors.red}not found${colors.reset}`);
  }

  const install = await confirm("  Install Redis?");
  if (!install) {
    console.log(`\n${colors.yellow}  Skipping Redis. Scheduled tasks and job queues will be unavailable.${colors.reset}`);
    return { redisUrl: "redis://localhost:6379" };
  }

  return await installRedis(platform);
}

async function startRedis(platform: Platform) {
  if (platform.os === "linux") {
    await exec("sudo systemctl start redis-server 2>/dev/null || sudo systemctl start redis 2>/dev/null", { throws: false });
  } else if (platform.os === "darwin") {
    await exec("brew services start redis", { throws: false });
  }
}

async function installRedis(platform: Platform): Promise<{ redisUrl: string }> {
  console.log(`\n  Installing Redis...`);

  if (platform.packageManager === "apt") {
    await exec("sudo apt-get install -y redis-server");
    await exec("sudo systemctl enable redis-server");
    await exec("sudo systemctl start redis-server");
  } else if (platform.packageManager === "brew") {
    await exec("brew install redis");
    await exec("brew services start redis");
  } else if (platform.packageManager === "dnf") {
    await exec("sudo dnf install -y redis");
    await exec("sudo systemctl enable redis");
    await exec("sudo systemctl start redis");
  } else {
    console.log(`  ${colors.yellow}Unsupported package manager. Please install Redis manually.${colors.reset}`);
    return { redisUrl: "redis://localhost:6379" };
  }

  // Configure Redis for BullMQ (noeviction policy)
  await exec('redis-cli CONFIG SET maxmemory-policy noeviction 2>/dev/null', { throws: false });

  console.log(`  ${colors.green}Redis installed.${colors.reset}`);
  return { redisUrl: "redis://localhost:6379" };
}

// ── Database Migrations ──────────────────────────────────────────────────────

async function runMigrations(databaseUrl: string) {
  console.log(`  Running database migrations...`);

  try {
    const migrationsDir = getMigrationsDir();
    if (!existsSync(migrationsDir)) {
      console.log(`  ${colors.yellow}Migrations folder not found at ${migrationsDir}. Skipping.${colors.reset}`);
      return;
    }

    // Use dynamic imports to load database modules
    const { default: postgres } = await import("postgres");
    const { drizzle } = await import("drizzle-orm/postgres-js");
    const { migrate } = await import("drizzle-orm/postgres-js/migrator");

    const client = postgres(databaseUrl, { max: 1 });
    const db = drizzle(client);

    // Enable pgvector extension
    await client`CREATE EXTENSION IF NOT EXISTS vector`;

    await migrate(db, { migrationsFolder: migrationsDir });

    await client.end();
    console.log(`  ${colors.green}Migrations complete.${colors.reset}`);
  } catch (err: any) {
    console.log(`  ${colors.yellow}Migration warning: ${err.message}${colors.reset}`);
    console.log(`  ${colors.dim}You can run migrations later with: opensentinel start${colors.reset}`);
  }
}

// ── Daemon Setup ─────────────────────────────────────────────────────────────

async function setupDaemon(platform: Platform, configDir: string) {
  const installDaemon = await confirm("  Install as system service (auto-start on boot)?");
  if (!installDaemon) {
    console.log(`  ${colors.dim}Skipped. Run manually with: opensentinel start${colors.reset}`);
    return;
  }

  if (platform.os === "linux") {
    await setupSystemd(configDir);
  } else if (platform.os === "darwin") {
    await setupLaunchd(configDir);
  } else {
    console.log(`  ${colors.yellow}Daemon setup not supported on this platform. Run manually with: opensentinel start${colors.reset}`);
  }
}

async function setupSystemd(configDir: string) {
  const bunPath = await which("bun") || "/usr/local/bin/bun";
  const opensentinelPath = await which("opensentinel") || `${bunPath} ${join(getPackageRoot(), "dist", "cli.js")}`;
  const user = process.env.USER || "root";

  const unit = `[Unit]
Description=OpenSentinel AI Assistant
After=network.target postgresql.service redis-server.service
Wants=postgresql.service redis-server.service

[Service]
Type=simple
User=${user}
WorkingDirectory=${configDir}
EnvironmentFile=${configDir}/.env
ExecStart=${opensentinelPath} start
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=opensentinel

[Install]
WantedBy=multi-user.target
`;

  const unitPath = "/etc/systemd/system/opensentinel.service";
  writeFileSync("/tmp/opensentinel.service", unit);
  await exec(`sudo cp /tmp/opensentinel.service ${unitPath}`);
  await exec("sudo systemctl daemon-reload");
  await exec("sudo systemctl enable opensentinel");

  console.log(`  ${colors.green}Systemd service installed.${colors.reset}`);
  console.log(`  ${colors.dim}Unit file: ${unitPath}${colors.reset}`);

  const startNow = await confirm("  Start OpenSentinel now?");
  if (startNow) {
    await exec("sudo systemctl start opensentinel");
    console.log(`  ${colors.green}Service started!${colors.reset}`);
    console.log(`  ${colors.dim}Logs: journalctl -u opensentinel -f${colors.reset}`);
  }
}

async function setupLaunchd(configDir: string) {
  const opensentinelPath = await which("opensentinel") || join(getPackageRoot(), "dist", "cli.js");

  const logsDir = join(configDir, "logs");
  if (!existsSync(logsDir)) {
    const { mkdirSync } = await import("node:fs");
    mkdirSync(logsDir, { recursive: true });
  }

  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>ai.opensentinel.daemon</string>
  <key>ProgramArguments</key>
  <array>
    <string>${opensentinelPath}</string>
    <string>start</string>
  </array>
  <key>WorkingDirectory</key>
  <string>${configDir}</string>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${logsDir}/opensentinel.log</string>
  <key>StandardErrorPath</key>
  <string>${logsDir}/opensentinel-error.log</string>
</dict>
</plist>`;

  const plistPath = join(homedir(), "Library", "LaunchAgents", "ai.opensentinel.daemon.plist");
  writeFileSync(plistPath, plist);

  console.log(`  ${colors.green}LaunchAgent installed.${colors.reset}`);
  console.log(`  ${colors.dim}Plist: ${plistPath}${colors.reset}`);

  const startNow = await confirm("  Start OpenSentinel now?");
  if (startNow) {
    await exec(`launchctl load ${plistPath}`);
    console.log(`  ${colors.green}Service started!${colors.reset}`);
    console.log(`  ${colors.dim}Logs: tail -f ${logsDir}/opensentinel.log${colors.reset}`);
  }
}
